# Generated by Django 4.2.7 on 2023-11-06 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('comision', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RenameModel(
            old_name='Curso',
            new_name='fondos_inversion',
        ),
        migrations.DeleteModel(
            name='estudiante',
        ),
        migrations.RenameField(
            model_name='fondos_inversion',
            old_name='comision',
            new_name='cant_activos',
        ),
    ]
