# Generated by Django 4.2.7 on 2023-11-06 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_acciones_bonos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='comision',
            new_name='Apellido',
        ),
    ]
