# Generated by Django 4.2.7 on 2023-11-06 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_remove_clientes_nombre_alter_clientes_apellido_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='Apellido',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='clientes',
            old_name='Nombre',
            new_name='nombre',
        ),
    ]
