# Generated by Django 4.2.7 on 2023-11-06 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_rename_apellido_clientes_apellido_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acciones',
            old_name='nombre',
            new_name='nombre_acciones',
        ),
        migrations.RenameField(
            model_name='bonos',
            old_name='nombre',
            new_name='nombre_bonos',
        ),
        migrations.RenameField(
            model_name='clientes',
            old_name='nombre',
            new_name='nombre_cliente',
        ),
        migrations.RenameField(
            model_name='fondos_inversion',
            old_name='nombre',
            new_name='nombre_fondo',
        ),
    ]
