# Generated by Django 4.2.7 on 2023-11-06 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_rename_nombre_acciones_nombre_acciones_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='clientes',
            new_name='Cliente',
        ),
    ]
