# Generated by Django 4.2.7 on 2023-11-07 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_rename_clientes_cliente'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='fondos_inversion',
            new_name='fondos',
        ),
    ]
